### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by peterjaap**
- Refactored extension
- Removed unneeded code by extending the original Downloadable class,
- Composerized extension
- Fixed phpcs/phpstan warnings

### CODE REVIEW

**Comment by peterjaap** [comment]
When merged, could you also create a release and add the package to Packagist.org?

**Comment by crankycyclops** [comment]
Thank you so much for doing this. I should have extended Downloadable from the beginning. I only have one small change to request before merging. I have another package on packagist, crankycyclops/m2-module-discount-code-url. To keep the naming style the same, can you name this crankycyclops/configurable-product?

**Comment by peterjaap** [comment]
@crankycyclops sure! Although I'm not sure how that makes it more consistent but okay :)

More consistent would be;
- `crankcyclops/m2-module-configurable-product`

Although the convention generally is `vendor/magento2-*`

I also added "downloadable" in there because that's relevant to what this extension does - it's about the combination of downloadable and configurable products.

So imho the best name would be `crankycyclops/magento2-configurable-downloadable-product` or maybe even more specific; `crankycyclops/magento2-configurable-downloadable-email-links`.

**Comment by crankycyclops** [comment]
Let's go with your first option, `crankycyclops/magento2-configurable-downloadable-product`

**Comment by peterjaap** [comment]
Done, good to go!

**Review by crankycyclops — APPROVED** [review]

**Comment by crankycyclops** [comment]
Sweet, thank you! Code is merged and I've submitted the package to packagist.

**Comment by crankycyclops** [comment]
I released this as 1.0.0.

**Pull request merged**
